version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - APP_PORT=8080
      - APP_HOST=0.0.0.0
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ./migrations:/root/migrations
    depends_on:
      - postgres-local
      - redis-local
    networks:
      - cbalite-network

  postgres-local:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=cba
      - POSTGRES_PASSWORD=cbaPREP2025
      - POSTGRES_DB=cbalite
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - cbalite-network

  redis-local:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - cbalite-network

volumes:
  postgres-data:
  redis-data:

networks:
  cbalite-network:
    driver: bridge